# Generated by Django 5.2.3 on 2025-06-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresult',
            name='choice',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pollresult',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
